### ISSUE TITLE
your not running whamg 

### ISSUE THREAD

**Issue by zeeev** [dence/snakemake_pipelines#1]

**Comment by dence** [comment]
It didn't compile out of the box for me, but I mean to go back and get it working.

**Comment by zeeev** [comment]
What's the error?

**Comment by dence** [comment]
It is the “narrowing conversion” error. I found a thread for this issue on the wham repository and added my input there. I’m going to try compiling with older versions of gcc. In my cursory google search, this problem seemed to be caused by compiling older C++ code with newer versions of gcc.

**Comment by dence** [comment]
The older gcc version that my HPC has is 4.7.2, and I got the same error compiling with that one.

**Comment by zeeev** [comment]
Thanks, I'm working in throwing the error.

**Comment by dence** [comment]
Now I can’t find zlib.h

**Comment by zeeev** [comment]
samtools also requires zlib.h it's looking for the linking flag -lz

**Comment by dence** [comment]
Turns out that zlib.h will only show up if you’re in a session on the cluster’s interactive nodes.
